// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPVfLUaFara9rqealFxjQtt4L0pe3UGbw',
    appId: '1:43626797578:web:7a058aa6cb834b64ee9df3',
    messagingSenderId: '43626797578',
    projectId: 'portfolio-6e957',
    authDomain: 'portfolio-6e957.firebaseapp.com',
    storageBucket: 'portfolio-6e957.firebasestorage.app',
    measurementId: 'G-EGBFNM3L01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNxzoEUWDqYE0b-KIFnZ-8SVA7pF74Ck',
    appId: '1:43626797578:android:1d2d0da195083e20ee9df3',
    messagingSenderId: '43626797578',
    projectId: 'portfolio-6e957',
    storageBucket: 'portfolio-6e957.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vlEf9KFG1FiDLhE2K9jLpGzr45OeONI',
    appId: '1:43626797578:ios:d2b07743e931d433ee9df3',
    messagingSenderId: '43626797578',
    projectId: 'portfolio-6e957',
    storageBucket: 'portfolio-6e957.firebasestorage.app',
    iosBundleId: 'com.example.portFolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vlEf9KFG1FiDLhE2K9jLpGzr45OeONI',
    appId: '1:43626797578:ios:d2b07743e931d433ee9df3',
    messagingSenderId: '43626797578',
    projectId: 'portfolio-6e957',
    storageBucket: 'portfolio-6e957.firebasestorage.app',
    iosBundleId: 'com.example.portFolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPVfLUaFara9rqealFxjQtt4L0pe3UGbw',
    appId: '1:43626797578:web:f149d6a3b87bc2f8ee9df3',
    messagingSenderId: '43626797578',
    projectId: 'portfolio-6e957',
    authDomain: 'portfolio-6e957.firebaseapp.com',
    storageBucket: 'portfolio-6e957.firebasestorage.app',
    measurementId: 'G-F65XNQDH5R',
  );
}
